ft-util update

diff --git a/ft-util/ft_util_inc_func b/ft-util/ft_util_inc_func
--- a/ft-util/ft_util_inc_func
+++ b/ft-util/ft_util_inc_func
@@ -94,6 +94,20 @@ function run_cmd_silent() {
 }
 export -f run_cmd_silent
 
+# Similar to run_cmd_silent but do output the command's stdout and stderr
+# Exit if failed
+function run_cmd_quiet() {
+    eval " $@" | $S_LOG -s warn -d "$S_NAME|[${*}]" -i
+    local exit_code=$?
+    if [ $exit_code -eq 0 ]; then
+        $S_LOG -s debug -d "$S_NAME" "[${*}] successful"
+    else
+        $S_LOG -s crit -d "$S_NAME" "[${*}] failed with EXIT_CODE=${exit_code}"
+        exit $exit_code
+    fi
+}
+export -f run_cmd_quiet
+
 # Run command, output simple log and result
 # Continue if failed
 function run_cmd_log_noexit() {
@@ -101,7 +115,8 @@ function run_cmd_log_noexit() {
     local exit_code=${PIPESTATUS[0]}
     if [ $exit_code -eq 0 ]; then
         $S_LOG -d "$S_NAME" "[${*}] successful"
-    else $S_LOG -s crit -d "$S_NAME" "[${*}] failed with EXIT_CODE=${exit_code}"; fi
+    else $S_LOG -s err -d "$S_NAME" "[${*}] failed with EXIT_CODE=${exit_code}"; fi
+    return $exit_code
 }
 export -f run_cmd_log_noexit
 
@@ -112,14 +127,15 @@ function run_cmd_nolog_noexit() {
     local exit_code=$?
     if [ $exit_code -eq 0 ]; then
         $S_LOG -d "$S_NAME" "[${*}] successful"
-    else $S_LOG -s crit -d "$S_NAME" "[${*}] failed with EXIT_CODE=${exit_code}"; fi
+    else $S_LOG -s err -d "$S_NAME" "[${*}] failed with EXIT_CODE=${exit_code}"; fi
+    return $exit_code
 }
 export -f run_cmd_nolog_noexit
 
 # If exist, cp to .bak
 # bak_if_exist path
 function bak_if_exist() {
-    [ -e "${1}" ] && run_cmd_silent cp "${1}" "${1}.bak"
+    [ -e "${1}" ] && run_cmd_silent cp --preserve "${1}" "${1}.bak"
 }
 export -f bak_if_exist
 
@@ -139,7 +155,7 @@ export -f mkdir_if_missing
 # show_bak_diff path_to_file
 function show_bak_diff() {
     if [ -e "${1}.bak" ]; then
-        diff --unified=0 "${1}.bak" "${1}" | $S_LOG -s warn -d "$S_NAME" -d "diff ${1}" -i
+        diff --unified=0 "${1}.bak" "${1}" | $S_LOG -s warn -d "$S_NAME" -d "diff ${1}" -i || : # `|| :` is a workaround to "ignore" the return code of 1 from diff when file are different.
     else
         $S_LOG -s warn -d "$S_NAME" -d "diff ${1}" "No bak found (okay for new files)"
     fi
@@ -165,3 +181,53 @@ function is_bak_diff() {
     fi
 }
 export -f is_bak_diff
+
+# Simple override of variable in files (Bash or Docker environement variable definitions)
+# override_var "path_file" "VAR=" "123"
+function override_var() {
+    if grep "${2}" ${1} &>/dev/null; then
+        sed -i "s|^${2}.*|${2}${3} # ${S_NAME}|g" ${1}
+    else
+        $S_LOG -s err -d "$S_NAME" -d "${1}" "Not found \"${2}\" in configuration file"
+    fi
+}
+export -f override_var
+
+# Will generate key if empty
+# Key should only be alphanumeric and without quotes
+# override_key "path_file" "VAR="
+function override_key() {
+    key=$(sed -nr "s|${2}([[:alnum:]]+).*|\1|p" ${1})
+    if [ -z "${key}" ]; then
+        key=$(openssl rand -hex 32)
+        $S_LOG -s warn -d "$S_NAME" -d "${1}" "[New key generated] ${2}${key}"
+    fi
+    override_var "${1}" "${2}" "${key}"
+}
+export -f override_key
+
+# Function to show a prompt with yes/no options
+function confirm {
+    if [ "${skip_confirm:-false}" = "true" ]; then
+        return 0
+    fi
+
+    local prompt="$1"
+    local choice
+
+    read -p "$prompt [y/N]: " -n 1 choice
+    echo
+
+    case "$choice" in
+    y | Y) return 0 ;;
+    n | N) return 1 ;;
+    *) confirm "$prompt" ;;
+    esac
+}
+export -f confirm
+
+# Function to pause the script execution
+pause() {
+    read -r -p "Press Enter to continue..." _
+}
+export -f pause
